# These are supported funding model platforms

github: jdnichollsc
patreon: proyecto26
open_collective: proyecto26
ko_fi: proyecto26
tidelift: npm/@proyecto26/animatable-component
liberapay: jdnichollsc
custom: paypal.me/jdnichollsc
